#!/usr/bin/env node
/**
 * Generated documentation: keeps the parts of `docs/` that can be derived from the repository
 * itself up to date, so nobody has to remember to edit them and an interrupted session leaves a
 * readable resume point behind.
 *
 *   docs/STATUS.md     where work stands now: branch, current stage and its open items (from
 *                      TASKS.md), uncommitted files, recent checkpoints, how to resume
 *   docs/CHANGELOG.md  project history, one entry per commit (from git)
 *   docs/README.md     index of every document and decision record, with titles
 *   docs/log/YYYY-MM.md  append-only work log (checkpoints and notes, newest last)
 *
 * Hand-written docs (plans, decisions, guides) are never touched. Output is deterministic for the
 * same repository state (ordinal sorting, no clock) except the log, which records when things
 * happened by design.
 *
 * Usage: node scripts/docs.mjs            refresh generated docs
 *        node scripts/docs.mjs log <text> append a work-log note, then refresh
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync, appendFileSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/** Paths (prefixes) this script writes; a checkpoint ignores changes that touch only these. */
export const GENERATED = ["docs/STATUS.md", "docs/CHANGELOG.md", "docs/README.md", "docs/log/"];

const HEADER = "<!-- Generated by scripts/docs.mjs. Do not edit by hand; run `pnpm docs`. -->\n\n";

function git(root, args) {
  try {
    return execFileSync("git", args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trimEnd();
  } catch {
    return "";
  }
}

function read(path) {
  return existsSync(path) ? readFileSync(path, "utf8").replace(/\r\n/g, "\n") : "";
}

/** Writes only when the content changed, so file times and editors stay quiet. */
function writeIfChanged(path, content) {
  if (read(path) === content) return false;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  return true;
}

const byOrdinal = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

/** First markdown heading of a file, without the leading #s. */
function titleOf(path) {
  const line = read(path).split("\n").find((l) => /^#\s/.test(l));
  return line ? line.replace(/^#+\s*/, "").trim() : "";
}

/** The first `## Now:` section of TASKS.md: heading, finish line and checklist. */
export function currentStage(tasks) {
  const lines = tasks.split("\n");
  const start = lines.findIndex((l) => /^## Now\b/.test(l));
  if (start < 0) return null;
  let end = lines.findIndex((l, i) => i > start && /^## /.test(l));
  if (end < 0) end = lines.length;
  const section = lines.slice(start + 1, end);
  const finish = [];
  let inFinish = false;
  for (const l of section) {
    if (/^\*\*(Finish line|Done means)/.test(l)) inFinish = true;
    else if (inFinish && (l.trim() === "" || /^- \[/.test(l))) break;
    if (inFinish) finish.push(l);
  }
  const open = section.filter((l) => /^- \[ \]/.test(l)).map((l) => l.replace(/^- \[ \]\s*/, ""));
  const done = section.filter((l) => /^- \[x\]/i.test(l)).length;
  return { title: lines[start].replace(/^## Now:?\s*/, ""), finish: finish.join(" ").replace(/\s+/g, " "), open, done };
}

function statusDoc(root) {
  const branch = git(root, ["rev-parse", "--abbrev-ref", "HEAD"]) || "unknown";
  const head = git(root, ["log", "-1", "--format=%h %s"]);
  const stage = currentStage(read(join(root, "TASKS.md")));
  const dirty = git(root, ["status", "--porcelain", "--untracked-files=all"])
    .split("\n")
    .filter(Boolean)
    .filter((l) => !GENERATED.some((g) => l.slice(3).startsWith(g)))
    .sort(byOrdinal);
  const ref = `refs/checkpoints/${branch}`;
  const checkpoints = git(root, ["log", "--first-parent", "-n", "10", "--format=%h %ad %s", "--date=format:%Y-%m-%d %H:%M", ref])
    .split("\n")
    .filter(Boolean);

  const out = [HEADER, "# Status\n\n"];
  out.push("Where work stands. Read this first after an interruption, then `TASKS.md`.\n\n");
  out.push(`- **Branch:** \`${branch}\`\n- **Last commit:** ${head ? `\`${head.split(" ")[0]}\` ${head.slice(head.indexOf(" ") + 1)}` : "none"}\n`);
  out.push(`- **Uncommitted files:** ${dirty.length}\n\n`);
  if (stage) {
    out.push(`## Current stage: ${stage.title}\n\n`);
    if (stage.finish) out.push(`${stage.finish}\n\n`);
    out.push(`${stage.done} done, ${stage.open.length} open.\n\n`);
    if (stage.open.length) out.push("Open items:\n\n" + stage.open.map((o) => `- [ ] ${o}`).join("\n") + "\n\n");
  } else {
    out.push("## Current stage\n\nNo `## Now:` section in `TASKS.md`.\n\n");
  }
  out.push("## Uncommitted work\n\n");
  out.push(dirty.length ? "```\n" + dirty.join("\n") + "\n```\n\n" : "Nothing uncommitted.\n\n");
  out.push("## Recent checkpoints\n\n");
  out.push(
    checkpoints.length
      ? checkpoints.map((c) => `- \`${c.slice(0, c.indexOf(" "))}\` ${c.slice(c.indexOf(" ") + 1)}`).join("\n") + "\n\n"
      : `None yet on \`${branch}\` (\`pnpm checkpoint\` makes one).\n\n`,
  );
  out.push("## How to resume\n\n");
  out.push("1. Read the open items above and the matching section of `TASKS.md`.\n");
  out.push("2. If files were lost, restore the last checkpoint: `git checkout " + ref + " -- .`\n");
  out.push("3. Run `pnpm typecheck` to see what the interrupted work left broken, then continue.\n");
  out.push("4. Details: `docs/process/interruptions.md`.\n");
  return out.join("");
}

function changelogDoc(root) {
  const raw = git(root, ["log", "--no-merges", "--date=short", "--format=%h%x1f%ad%x1f%s%x1f%b%x1e", "HEAD"]);
  const out = [HEADER, "# Changelog\n\n", "Every change to the project, newest first, generated from the git history.\n"];
  let month = "";
  for (const record of raw.split("\x1e")) {
    const [hash, date, subject, body = ""] = record.replace(/^\n/, "").split("\x1f");
    if (!hash) continue;
    if (date.slice(0, 7) !== month) {
      month = date.slice(0, 7);
      out.push(`\n## ${month}\n`);
    }
    out.push(`\n### ${subject}\n\n\`${hash}\` · ${date}\n`);
    const lines = body
      .split("\n")
      .filter((l) => l.trim() && !/^(Co-Authored-By|Claude-Session|Signed-off-by):/i.test(l.trim()));
    if (lines.length) {
      const shown = lines.slice(0, 15);
      out.push("\n" + shown.join("\n") + (lines.length > shown.length ? `\n\n…${lines.length - shown.length} more lines in the commit.` : "") + "\n");
    }
  }
  return out.join("");
}

function indexDoc(root) {
  const docs = join(root, "docs");
  const list = (dir) =>
    existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".md")).sort(byOrdinal) : [];
  const entry = (rel) => `- [${titleOf(join(docs, rel)) || rel}](${rel})`;
  const top = list(docs).filter((f) => !["README.md", "STATUS.md", "CHANGELOG.md"].includes(f));
  const out = [HEADER, "# Documentation\n\n"];
  out.push("Start with [STATUS.md](STATUS.md) (where work stands) and the root `TASKS.md` (the checklist).\n\n");
  out.push("## Plans and guides\n\n" + top.map(entry).join("\n") + "\n\n");
  const process = list(join(docs, "process"));
  if (process.length) out.push("## How we work\n\n" + process.map((f) => entry(`process/${f}`)).join("\n") + "\n\n");
  const decisions = list(join(docs, "decisions"));
  out.push("## Decision records\n\n" + decisions.map((f) => entry(`decisions/${f}`)).join("\n") + "\n\n");
  const logs = list(join(docs, "log")).reverse();
  out.push("## Generated\n\n- [Status](STATUS.md): current stage, open items, uncommitted work, checkpoints\n");
  out.push("- [Changelog](CHANGELOG.md): full history from git\n");
  if (logs.length) out.push(logs.map((f) => `- [Work log ${f.replace(/\.md$/, "")}](log/${f})`).join("\n") + "\n");
  return out.join("");
}

/** Refreshes every generated doc; returns the paths that changed. */
export function updateDocs(root) {
  const docs = join(root, "docs");
  const changed = [];
  if (writeIfChanged(join(docs, "STATUS.md"), statusDoc(root))) changed.push("docs/STATUS.md");
  if (writeIfChanged(join(docs, "CHANGELOG.md"), changelogDoc(root))) changed.push("docs/CHANGELOG.md");
  if (writeIfChanged(join(docs, "README.md"), indexDoc(root))) changed.push("docs/README.md");
  return changed;
}

/** Appends one timestamped line to this month's work log. */
export function appendLog(root, text) {
  const now = new Date();
  const pad = (n) => String(n).padStart(2, "0");
  const month = `${now.getFullYear()}-${pad(now.getMonth() + 1)}`;
  const path = join(root, "docs", "log", `${month}.md`);
  if (!existsSync(path)) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, `# Work log ${month}\n\nAppend-only: checkpoints and notes, newest last. Written by \`pnpm checkpoint\` and \`pnpm log\`.\n\n`);
  }
  const stamp = `${month}-${pad(now.getDate())} ${pad(now.getHours())}:${pad(now.getMinutes())}`;
  appendFileSync(path, `- ${stamp} · ${text.replace(/\s+/g, " ").trim()}\n`);
}

const isMain =
  process.argv[1] !== undefined &&
  resolve(fileURLToPath(import.meta.url)).toLowerCase() === resolve(process.argv[1]).toLowerCase();
if (isMain) {
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const [command, ...rest] = process.argv.slice(2);
  if (command === "log") {
    if (!rest.length) {
      console.error("usage: node scripts/docs.mjs log <text>");
      process.exit(1);
    }
    appendLog(root, rest.join(" "));
  }
  const changed = updateDocs(root);
  console.log(changed.length ? `Updated ${changed.join(", ")}` : "Generated docs already up to date.");
}
